version: '3'
services:
  biblereadings:
    image: andyschott/services:biblereadings
    expose:
      - "80"
    env_file:
      - ./biblereadings/environment.txt
    volumes:
      - ./biblereadings/data/:/root/data/
    networks:
      - my-network
  payoutbot:
    image: andyschott/services:payoutbot
    expose:
      - "80"
    env_file:
      - ./payoutbot/environment.txt
    volumes:
      - ./payoutbot/data:/app/data/
    networks:
      - my-network
  nginx:
    depends_on:
      - biblereadings
      - payoutbot
    image: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    networks:
      - my-network
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
networks:
  my-network: